package tech.pixela.jetfm.ui.theme

import androidx.compose.ui.graphics.Color

/* Light colors */
val LightPrimary = Color(0xFFbf0904)
val LightOnPrimary = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFFffdad3)
val LightOnPrimaryContainer = Color(0xFF410000)
val LightSecondary = Color(0xFF764b9c)
val LightOnSecondary = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFFf2daff)
val LightOnSecondaryContainer = Color(0xFF2c0050)
val LightTertiary = Color(0xFF0053da)
val LightOnTertiary = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFFdae2ff)
val LightOnTertiaryContainer = Color(0xFF00174c)
val LightError = Color(0xFFba1b1b)
val LightErrorContainer = Color(0xFFffdad4)
val LightOnError = Color(0xFFffffff)
val LightOnErrorContainer = Color(0xFF410001)
val LightBackground = Color(0xFFfbfdfd)
val LightOnBackground = Color(0xFF191c1d)
val LightSurface = Color(0xFFfbfdfd)
val LightOnSurface = Color(0xFF191c1d)
val LightSurfaceVariant = Color(0xFFf5deda)
val LightOnSurfaceVariant = Color(0xFF534341)
val LightOutline = Color(0xFF867370)
val LightInverseOnSurface = Color(0xFFeff1f1)
val LightInverseSurface = Color(0xFF2d3132)

/* Dark colors */
val DarkPrimary = Color(0xFFffb4a6)
val DarkOnPrimary = Color(0xFF690000)
val DarkPrimaryContainer = Color(0xFF940000)
val DarkOnPrimaryContainer = Color(0xFFffdad3)
val DarkSecondary = Color(0xFFe0b6ff)
val DarkOnSecondary = Color(0xFF45196a)
val DarkSecondaryContainer = Color(0xFF5d3382)
val DarkOnSecondaryContainer = Color(0xFFf2daff)
val DarkTertiary = Color(0xFFb1c5ff)
val DarkOnTertiary = Color(0xFF002a79)
val DarkTertiaryContainer = Color(0xFF003ea8)
val DarkOnTertiaryContainer = Color(0xFFdae2ff)
val DarkError = Color(0xFFffb4a9)
val DarkErrorContainer = Color(0xFF930006)
val DarkOnError = Color(0xFF680003)
val DarkOnErrorContainer = Color(0xFFffdad4)
val DarkBackground = Color(0xFF191c1d)
val DarkOnBackground = Color(0xFFe0e3e3)
val DarkSurface = Color(0xFF191c1d)
val DarkOnSurface = Color(0xFFe0e3e3)
val DarkSurfaceVariant = Color(0xFF534341)
val DarkOnSurfaceVariant = Color(0xFFd8c2be)
val DarkOutline = Color(0xFFa08c89)
val DarkInverseOnSurface = Color(0xFF191c1d)
val DarkInverseSurface = Color(0xFFe0e3e3)